
import pandas as pd
import numpy as np  
pd.set_option('display.width', 10000)
pd.set_option('display.max_columns', None) 


# Setup
# ******************************************************
# ******************************************************

#> Data TexasCensus.csv 
texasCensusDf = pd.read_csv('TexasCensus.csv') 

#> VisualizeAllColumns 
# Code added to start of file to display all columns for dataframes 

#> ColumnHeaders 
# Label (Grouping)
# Texas!!Total!!Estimate
# Texas!!Total!!Margin of Error
# Texas!!Percent!!Estimate
# Texas!!Percent!!Margin of Error
# Texas!!Male!!Estimate
# Texas!!Male!!Margin of Error
# Texas!!Percent Male!!Estimate
# Texas!!Percent Male!!Margin of Error
# Texas!!Female!!Estimate
# Texas!!Female!!Margin of Error
# Texas!!Percent Female!!Estimate
# Texas!!Percent Female!!Margin of Error
# Harris County, Texas!!Total!!Estimate
# Harris County, Texas!!Total!!Margin of Error
# Harris County, Texas!!Percent!!Estimate
# Harris County, Texas!!Percent!!Margin of Error
# Harris County, Texas!!Male!!Estimate
# Harris County, Texas!!Male!!Margin of Error
# Harris County, Texas!!Percent Male!!Estimate
# Harris County, Texas!!Percent Male!!Margin of Error
# Harris County, Texas!!Female!!Estimate
# Harris County, Texas!!Female!!Margin of Error
# Harris County, Texas!!Percent Female!!Estimate
# Harris County, Texas!!Percent Female!!Margin of Error 



# Example 1
# Remove non-standard character from the entire dataframe.
# Sometimes these are introduced accidentally or intentionally in a datset
# Seed being used: #> RemoveWeirdCharacters 
# ******************************************************
# ******************************************************

#> Visualize 
print(texasCensusDf.head()) #)1 
##***          Label (Grouping) Texas!!Total!!Estimate Texas!!Total!!Margin of Error Texas!!Percent!!Estimate Texas!!Percent!!Margin of Error Texas!!Male!!Estimate Texas!!Male!!Margin of Error Texas!!Percent Male!!Estimate Texas!!Percent Male!!Margin of Error Texas!!Female!!Estimate Texas!!Female!!Margin of Error Texas!!Percent Female!!Estimate Texas!!Percent Female!!Margin of Error Harris County, Texas!!Total!!Estimate Harris County, Texas!!Total!!Margin of Error Harris County, Texas!!Percent!!Estimate Harris County, Texas!!Percent!!Margin of Error Harris County, Texas!!Male!!Estimate Harris County, Texas!!Male!!Margin of Error Harris County, Texas!!Percent Male!!Estimate Harris County, Texas!!Percent Male!!Margin of Error Harris County, Texas!!Female!!Estimate Harris County, Texas!!Female!!Margin of Error Harris County, Texas!!Percent Female!!Estimate Harris County, Texas!!Percent Female!!Margin of Error
##*** 0        Total population             30,503,301                         *****                      (X)                             (X)            15,213,144                       ▒9,765                           (X)                                  (X)              15,290,157                         ▒9,765                             (X)                                    (X)                             4,835,125                                        *****                                     (X)                                            (X)                            2,400,063                                        ▒399                                          (X)                                                (X)                               2,435,062                                          ▒399                                            (X)                                                (X)   
##*** 1                 ááááAGE                    NaN                           NaN                      NaN                             NaN                   NaN                          NaN                           NaN                                  NaN                     NaN                            NaN                             NaN                                    NaN                                   NaN                                          NaN                                     NaN                                            NaN                                  NaN                                         NaN                                          NaN                                                NaN                                     NaN                                           NaN                                            NaN                                                NaN   
##*** 2   ááááááááUnder 5 years              1,913,591                        ▒5,284                     6.3%                            ▒0.1               977,677                       ▒5,956                          6.4%                                 ▒0.1                 935,914                         ▒5,679                            6.1%                                   ▒0.1                               323,950                                         ▒193                                    6.7%                                           ▒0.1                              165,335                                        ▒292                                         6.9%                                               ▒0.1                                 158,615                                          ▒232                                           6.5%                                               ▒0.1   
##*** 3    áááááááá5 to 9 years              2,066,208                       ▒21,294                     6.8%                            ▒0.1             1,049,536                      ▒17,905                          6.9%                                 ▒0.1               1,016,672                        ▒15,989                            6.6%                                   ▒0.1                               342,195                                       ▒9,743                                    7.1%                                           ▒0.2                              170,916                                      ▒7,030                                         7.1%                                               ▒0.3                                 171,279                                        ▒6,821                                           7.0%                                               ▒0.3   
##*** 4  áááááááá10 to 14 years              2,205,759                       ▒21,338                     7.2%                            ▒0.1             1,133,522                      ▒17,962                          7.5%                                 ▒0.1               1,072,237                        ▒15,144                            7.0%                                   ▒0.1                               353,847                                       ▒9,749                                    7.3%                                           ▒0.2                              182,978                                      ▒7,001                                         7.6%                                               ▒0.3                                 170,869                                        ▒6,837                                           7.0%                                               ▒0.3

#> RemoveWeirdCharacters 
for column in texasCensusDf.columns:
    texasCensusDf[column] = texasCensusDf[column].str.replace(r'[^\x00-\x7F]+', '', regex=True) 

#> Visualize 
print(texasCensusDf.head()) #)2 
##***    Label (Grouping) Texas!!Total!!Estimate Texas!!Total!!Margin of Error Texas!!Percent!!Estimate Texas!!Percent!!Margin of Error Texas!!Male!!Estimate Texas!!Male!!Margin of Error Texas!!Percent Male!!Estimate Texas!!Percent Male!!Margin of Error Texas!!Female!!Estimate Texas!!Female!!Margin of Error Texas!!Percent Female!!Estimate Texas!!Percent Female!!Margin of Error Harris County, Texas!!Total!!Estimate Harris County, Texas!!Total!!Margin of Error Harris County, Texas!!Percent!!Estimate Harris County, Texas!!Percent!!Margin of Error Harris County, Texas!!Male!!Estimate Harris County, Texas!!Male!!Margin of Error Harris County, Texas!!Percent Male!!Estimate Harris County, Texas!!Percent Male!!Margin of Error Harris County, Texas!!Female!!Estimate Harris County, Texas!!Female!!Margin of Error Harris County, Texas!!Percent Female!!Estimate Harris County, Texas!!Percent Female!!Margin of Error
##*** 0  Total population             30,503,301                         *****                      (X)                             (X)            15,213,144                        9,765                           (X)                                  (X)              15,290,157                          9,765                             (X)                                    (X)                             4,835,125                                        *****                                     (X)                                            (X)                            2,400,063                                         399                                          (X)                                                (X)                               2,435,062                                           399                                            (X)                                                (X)   
##*** 1               AGE                    NaN                           NaN                      NaN                             NaN                   NaN                          NaN                           NaN                                  NaN                     NaN                            NaN                             NaN                                    NaN                                   NaN                                          NaN                                     NaN                                            NaN                                  NaN                                         NaN                                          NaN                                                NaN                                     NaN                                           NaN                                            NaN                                                NaN   
##*** 2     Under 5 years              1,913,591                         5,284                     6.3%                             0.1               977,677                        5,956                          6.4%                                  0.1                 935,914                          5,679                            6.1%                                    0.1                               323,950                                          193                                    6.7%                                            0.1                              165,335                                         292                                         6.9%                                                0.1                                 158,615                                           232                                           6.5%                                                0.1   
##*** 3      5 to 9 years              2,066,208                        21,294                     6.8%                             0.1             1,049,536                       17,905                          6.9%                                  0.1               1,016,672                         15,989                            6.6%                                    0.1                               342,195                                        9,743                                    7.1%                                            0.2                              170,916                                       7,030                                         7.1%                                                0.3                                 171,279                                         6,821                                           7.0%                                                0.3   
##*** 4    10 to 14 years              2,205,759                        21,338                     7.2%                             0.1             1,133,522                       17,962                          7.5%                                  0.1               1,072,237                         15,144                            7.0%                                    0.1                               353,847                                        9,749                                    7.3%                                            0.2                              182,978                                       7,001                                         7.6%                                                0.3                                 170,869                                         6,837                                           7.0%                                                0.3



# Example 2
# Remove non-standard character from specified columns.
# Sometimes these are introduced accidentally or intentionally in a datset
# Seed being used: #> RemoveWeirdCharacters Label  (Grouping) Texas  Total  Margin  of  Error 
# ******************************************************

# Reset the dataframe
#> Data TexasCensus.csv 
texasCensusDf = pd.read_csv('TexasCensus.csv') 

#> ColumnRename --replace !! --with ' ' 
texasCensusDf.columns = texasCensusDf.columns.str.replace('!!', ' ') 

#> Visualize 
print(texasCensusDf.head()) #)3 
##***          Label (Grouping) Texas Total Estimate Texas Total Margin of Error Texas Percent Estimate Texas Percent Margin of Error Texas Male Estimate Texas Male Margin of Error Texas Percent Male Estimate Texas Percent Male Margin of Error Texas Female Estimate Texas Female Margin of Error Texas Percent Female Estimate Texas Percent Female Margin of Error Harris County, Texas Total Estimate Harris County, Texas Total Margin of Error Harris County, Texas Percent Estimate Harris County, Texas Percent Margin of Error Harris County, Texas Male Estimate Harris County, Texas Male Margin of Error Harris County, Texas Percent Male Estimate Harris County, Texas Percent Male Margin of Error Harris County, Texas Female Estimate Harris County, Texas Female Margin of Error Harris County, Texas Percent Female Estimate Harris County, Texas Percent Female Margin of Error
##*** 0        Total population           30,503,301                       *****                    (X)                           (X)          15,213,144                     ▒9,765                         (X)                                (X)            15,290,157                       ▒9,765                           (X)                                  (X)                           4,835,125                                      *****                                   (X)                                          (X)                          2,400,063                                      ▒399                                        (X)                                               (X)                            2,435,062                                        ▒399                                          (X)                                                (X) 
##*** 1                 ááááAGE                  NaN                         NaN                    NaN                           NaN                 NaN                        NaN                         NaN                                NaN                   NaN                          NaN                           NaN                                  NaN                                 NaN                                        NaN                                   NaN                                          NaN                                NaN                                       NaN                                        NaN                                               NaN                                  NaN                                         NaN                                          NaN                                                NaN 
##*** 2   ááááááááUnder 5 years            1,913,591                      ▒5,284                   6.3%                          ▒0.1             977,677                     ▒5,956                        6.4%                               ▒0.1               935,914                       ▒5,679                          6.1%                                 ▒0.1                             323,950                                       ▒193                                  6.7%                                         ▒0.1                            165,335                                      ▒292                                       6.9%                                              ▒0.1                              158,615                                        ▒232                                         6.5%                                               ▒0.1 
##*** 3    áááááááá5 to 9 years            2,066,208                     ▒21,294                   6.8%                          ▒0.1           1,049,536                    ▒17,905                        6.9%                               ▒0.1             1,016,672                      ▒15,989                          6.6%                                 ▒0.1                             342,195                                     ▒9,743                                  7.1%                                         ▒0.2                            170,916                                    ▒7,030                                       7.1%                                              ▒0.3                              171,279                                      ▒6,821                                         7.0%                                               ▒0.3 
##*** 4  áááááááá10 to 14 years            2,205,759                     ▒21,338                   7.2%                          ▒0.1           1,133,522                    ▒17,962                        7.5%                               ▒0.1             1,072,237                      ▒15,144                          7.0%                                 ▒0.1                             353,847                                     ▒9,749                                  7.3%                                         ▒0.2                            182,978                                    ▒7,001                                       7.6%                                              ▒0.3                              170,869                                      ▒6,837                                         7.0%                                               ▒0.3

#> RemoveWeirdCharacters Label  (Grouping) Texas  Total  Margin  of  Error 
texasCensusDf['Label (Grouping)'] = texasCensusDf['Label (Grouping)'].str.replace(r'[^\x00-\x7F]+', '', regex=True)
texasCensusDf['Texas Total Margin of Error'] = texasCensusDf['Texas Total Margin of Error'].str.replace(r'[^\x00-\x7F]+', '', regex=True) 

#> Visualize 
print(texasCensusDf.head()) #)4 
##***    Label (Grouping) Texas Total Estimate Texas Total Margin of Error Texas Percent Estimate Texas Percent Margin of Error Texas Male Estimate Texas Male Margin of Error Texas Percent Male Estimate Texas Percent Male Margin of Error Texas Female Estimate Texas Female Margin of Error Texas Percent Female Estimate Texas Percent Female Margin of Error Harris County, Texas Total Estimate Harris County, Texas Total Margin of Error Harris County, Texas Percent Estimate Harris County, Texas Percent Margin of Error Harris County, Texas Male Estimate Harris County, Texas Male Margin of Error Harris County, Texas Percent Male Estimate Harris County, Texas Percent Male Margin of Error Harris County, Texas Female Estimate Harris County, Texas Female Margin of Error Harris County, Texas Percent Female Estimate Harris County, Texas Percent Female Margin of Error
##*** 0  Total population           30,503,301                       *****                    (X)                           (X)          15,213,144                     ▒9,765                         (X)                                (X)            15,290,157                       ▒9,765                           (X)                                  (X)                           4,835,125                                      *****                                   (X)                                          (X)                          2,400,063                                      ▒399                                        (X)                                               (X)                            2,435,062                                        ▒399                                          (X)                                                (X) 
##*** 1               AGE                  NaN                         NaN                    NaN                           NaN                 NaN                        NaN                         NaN                                NaN                   NaN                          NaN                           NaN                                  NaN                                 NaN                                        NaN                                   NaN                                          NaN                                NaN                                       NaN                                        NaN                                               NaN                                  NaN                                         NaN                                          NaN                                                NaN 
##*** 2     Under 5 years            1,913,591                       5,284                   6.3%                          ▒0.1             977,677                     ▒5,956                        6.4%                               ▒0.1               935,914                       ▒5,679                          6.1%                                 ▒0.1                             323,950                                       ▒193                                  6.7%                                         ▒0.1                            165,335                                      ▒292                                       6.9%                                              ▒0.1                              158,615                                        ▒232                                         6.5%                                               ▒0.1 
##*** 3      5 to 9 years            2,066,208                      21,294                   6.8%                          ▒0.1           1,049,536                    ▒17,905                        6.9%                               ▒0.1             1,016,672                      ▒15,989                          6.6%                                 ▒0.1                             342,195                                     ▒9,743                                  7.1%                                         ▒0.2                            170,916                                    ▒7,030                                       7.1%                                              ▒0.3                              171,279                                      ▒6,821                                         7.0%                                               ▒0.3 
##*** 4    10 to 14 years            2,205,759                      21,338                   7.2%                          ▒0.1           1,133,522                    ▒17,962                        7.5%                               ▒0.1             1,072,237                      ▒15,144                          7.0%                                 ▒0.1                             353,847                                     ▒9,749                                  7.3%                                         ▒0.2                            182,978                                    ▒7,001                                       7.6%                                              ▒0.3                              170,869                                      ▒6,837                                         7.0%                                               ▒0.3
